[mcp_servers.msw-maker-mcp]
command = "/bin/sh"
args = ["-c", "exec \"$1\"", "msw-maker-mcp", "/Library/Application Support/Nexon/MapleStory Worlds/MapleStory Worlds.app/Contents/MacOS/MakerMCP"]

[mcp_servers.msw-mcp]
url = "https://msw-mcp.nexon.com/mcp"
http_headers = { "Authorization" = "Bearer e3a4855636ec47f4b8a82ecd4569a283" }

[mcp_servers.msw-mcp.tools.asset_list_account_resources]
approval_mode = "approve"

[mcp_servers.msw-mcp.tools.asset_get_account_resource_metadata_bulk]
approval_mode = "approve"

[mcp_servers.msw-mcp.tools.asset_get_account_thumbnail]
approval_mode = "approve"

[mcp_servers.msw-mcp.tools.mlua_api_retriever]
approval_mode = "approve"

[mcp_servers.msw-mcp.tools.mlua_document_retriever]
approval_mode = "approve"
